### ISSUE TITLE
Add options to core methods

### ISSUE THREAD

**Issue by pjhartzell** [pjhartzell/raster-footprint#3]
~~Currently, the only place to specify footprint options is in the constructor. So you can't create a `RasterFootprint` class and run the `footprint` method several times with different option values. You need to create a new class each time, which seems a bit clunky, particularly if you are using an alternative constructor that reads data from a file each time.~~

~~We could:~~
~~1. Allow over-riding any `self` assigned options (assigned during class initialization) with options passed to the `footprint()` and other class methods.
2. Only accept the required arguments in class initialization. The optional arguments would always be passed to the `footprint()` and other class methods.~~

As pointed out by @gadomski below, we can update the option attributes directly. I think, for now, there is not a compelling reason to modify the current structure and behavior.

**Comment by gadomski** [comment]
Two other options:

3. Keep it as-is, and encourage folks update attributes directly:
```python
raster_footprint = RasterFootprint(mask_array, crs, transform)
raster_footprint.simplify_tolerance = 42.0
```
4. Builder pattern
```python
raster_footprint = RasterFootprint(mask_array, crs, transform).simplify_tolerance(42.0)
```

Any problems with option 3? To me, it seems the easiest and the cleanest (since it's already possible).

**Comment by gadomski** [comment]
I agree that this feels natural:

```python
raster_footprint = RasterFootprint(mask_array, crs, transform)
footprint = RasterFootprint.footprint(precision=4, simplify_tolerance=0.001)
```
